/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.23
 * Generated at: 2015-07-28 06:01:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1438060449621L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1438043030880L));
    _jspx_dependants.put("/user/loginForm.jsp", Long.valueOf(1438060907752L));
    _jspx_dependants.put("/user/loginSuccess.jsp", Long.valueOf(1438063246598L));
    _jspx_dependants.put("jar:file:/C:/ncs_스마트문화앱_개발자양성과정/7_Servlet_JSP/workspace/boardProject/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>미니 프로젝트</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write(" <head>\r\n");
      out.write("  <title> 탭메뉴 </title>\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("\t#menu {\r\n");
      out.write("\t\twidth: 960px;\r\n");
      out.write("\t\theight: 40px;\r\n");
      out.write("\t\tclear: both;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tul.navi {\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\twidth: 960px;\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t\tlist-style: none;\r\n");
      out.write("\t\tbackground: #39F;\r\n");
      out.write("\t\t-moz-border-radius-topright: 10px;\r\n");
      out.write("\t\t-webkit-border-top-right-radius: 10px;\r\n");
      out.write("\t\t-moz-border-radius-topleft: 10px;\r\n");
      out.write("\t\t-webkit-border-top-left-radius: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tul.navi li {\r\n");
      out.write("\t\tdisplay: inline;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tul.navi li a {\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tfont: bold 14px 굴림;\r\n");
      out.write("\t\tline-height: 40px;\r\n");
      out.write("\t\tcolor: #fff;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\ttext-shadow: 1px 1px 1px #880000;\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tpadding: 0 30px;\r\n");
      out.write("\t\tbackground: #39F;\r\n");
      out.write("\t\t-moz-border-radius-topright: 10px;\r\n");
      out.write("\t\t-webkit-border-top-right-radius: 10px;\r\n");
      out.write("\t\t-moz-border-radius-topleft: 10px;\r\n");
      out.write("\t\t-webkit-border-top-left-radius: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tul.navi .current a, ul.navi li:hover > a { \r\n");
      out.write("\t\tcolor: #fff;\r\n");
      out.write("\t\ttext-decoration: none; \r\n");
      out.write("\t\ttext-shadow: 1px 1px 1px #330000; \r\n");
      out.write("\t\tbackground: #36F; \r\n");
      out.write("\t\t-moz-border-radius-topright: 10px; \r\n");
      out.write("\t\t-webkit-border-top-right-radius: 10px;\r\n");
      out.write("\t\t-moz-border-radius-topleft: 10px;\r\n");
      out.write("\t\t-webkit-border-top-left-radius: 10px; \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tul.navi ul { display: none; }\r\n");
      out.write("\t\r\n");
      out.write("\tul.navi li:hover > ul {\r\n");
      out.write("\t\tposition: absolute; \r\n");
      out.write("\t\tdisplay: block; \r\n");
      out.write("\t\twidth: 920px; \r\n");
      out.write("\t\theight: 45px; \r\n");
      out.write("\t\tmargin: 40px 0 0 0; \r\n");
      out.write("\t\tbackground: #33F; \r\n");
      out.write("\t\t-moz-border-radius-bottomright: 10px;\r\n");
      out.write("\t\t-webkit-border-bottom-right-radius: 10px;\r\n");
      out.write("\t\t-moz-border-radius-bottomleft: 10px;\r\n");
      out.write("\t\t-webkit-border-bottom-left-radius: 10px; \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tul.navi li:hover > ul li a {\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tfont: bold 14px 굴림;\r\n");
      out.write("\t\tline-height: 45px;\r\n");
      out.write("\t\tcolor: #fff;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\ttext-shadow: 1px 1px 1px #110000;\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tpadding: 0 30px 0 0;\r\n");
      out.write("\t\tbackground: #33F;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tul.navi li:hover > ul li a:hover {\r\n");
      out.write("\t\tcolor: #ff0000;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\ttext-shadow: none;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("  </style>\r\n");
      out.write(" </head>\r\n");
      out.write("\r\n");
      out.write(" <body>\r\n");
      out.write("  <h2>Mini Web Project</h2>\r\n");
      out.write("  <hr/>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<ul class=\"navi\">\r\n");
      out.write("\t\t\t<li><a href=\"/board/index.jsp\"> Home </a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"> 쇼핑</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"> 핸드폰</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"> 악세사리</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"> 신발</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"> 가전제품</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"> 게시판</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"> 답글게시판 </a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"> 공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"> 사진게시판</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"> 방명록</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li><a href=\"#\"> 회원서비스</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write(" </body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /index.jsp(13,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t");
        out.write("\r\n");
        out.write("<!DOCTYPE html>\n");
        out.write("<html>\n");
        out.write("<head>\r\n");
        out.write("<meta charset=\"UTF-8\">\n");
        out.write("<title>로그인 페이지</title>\n");
        out.write("</head>\n");
        out.write("<body>\r\n");
        out.write("<form name=\"loginform\" action=\"/board/first\" method=\"post\"  style=\"margin-top: 45px;align: rigth;\">\r\n");
        out.write("<input type=\"hidden\" name=\"action\" value=\"login\"/>\r\n");
        out.write("<center>\n");
        out.write("<table border=0  bgcolor=\"#97cbff\" style=\"float: right;\">\r\n");
        out.write("\t<tr>\r\n");
        out.write("\t\t<td colspan=\"2\" align=center>\r\n");
        out.write("\t\t\t<b><font size=5>로그인</font></b>\r\n");
        out.write("\t\t</td>\r\n");
        out.write("\t</tr>\r\n");
        out.write("\t<tr><td>아이디 : </td><td><input type=\"text\" name=\"loginId\"/></td></tr>\r\n");
        out.write("\t<tr><td>비밀번호 : </td><td><input type=\"password\" name=\"loginPwd\"/></td></tr>\r\n");
        out.write("\t<tr>\r\n");
        out.write("\t\t<td colspan=\"2\" align=center>\r\n");
        out.write("\t\t\t<a href=\"javascript:loginform.submit()\">로그인</a>&nbsp;&nbsp;\r\n");
        out.write("\t\t\t<a href=\"/board/first?action=uinsert\">회원가입</a>\r\n");
        out.write("\t\t</td>\r\n");
        out.write("\t</tr>\r\n");
        out.write("</table>\r\n");
        out.write("</center>\r\n");
        out.write("</form>\n");
        out.write("</body>\n");
        out.write("</html>");
        out.write('\r');
        out.write('\n');
        out.write('	');
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /index.jsp(16,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t");
        out.write("\r\n");
        out.write("<!DOCTYPE html>    \r\n");
        out.write("<html>\r\n");
        out.write("<head>\r\n");
        out.write("<meta charset=\"UTF-8\">\r\n");
        out.write("<title>로그인 성공</title>\r\n");
        out.write("</head>\r\n");
        out.write("<body>\r\n");
        out.write("\r\n");
        out.write("<table border=0  bgcolor=\"#97cbff\" style=\"float: right;margin-top: 45px;\">\r\n");
        out.write("\t<tr>\r\n");
        out.write("\t\t<td colspan=\"2\" align=center>\r\n");
        out.write("\t\t\t<b><font size=5>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write(" 님</font></b>\r\n");
        out.write("\t\t</td>\r\n");
        out.write("\t</tr>\r\n");
        out.write("\t<tr><td>메일</td><td>카페</td></tr>\r\n");
        out.write("\t<tr><td>쪽지</td><td>현재 포인트</td></tr>\r\n");
        out.write("\t<tr>\r\n");
        out.write("\t\t<td colspan=\"2\" align=center>\r\n");
        out.write("\t\t\t<a href=\"/board/first?action=logout\">로그아웃</a>&nbsp;&nbsp;\r\n");
        out.write("\t\t\t<a href=\"/board/first?action=udetail\">회원정보보기</a>\r\n");
        out.write("\t\t</td>\r\n");
        out.write("\t</tr>\r\n");
        out.write("</table>\r\n");
        out.write("</center>\r\n");
        out.write("</form>\r\n");
        out.write("</body>\r\n");
        out.write("</html>");
        out.write('\r');
        out.write('\n');
        out.write('	');
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
