--1
SELECT (SELECT COUNT(*) FROM TB_BOOK)+ (SELECT COUNT(*) FROM TB_PUBLISHER) + 
        (SELECT COUNT(*) FROM TB_WRITER) + (SELECT COUNT(*) FROM TB_BOOK_AUTHOR) "총 데이터건 수"
FROM DUAL; 

--2
DESC USER_TABLES;

SELECT * FROM USER_CONSTRAINTS;

SELECT * FROM USER_CATALOG;

SELECT * FROM ALL_TABLES;

SELECT * FROM USER_OBJECTS;


SELECT TABLE_NAME,COLUMN_NAME, DATA_TYPE, NULLABLE, DATA_DEFAULT FROM ALL_TAB_COLUMNS;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, R_CONSTRAINT_NAME FROM USER_CONSTRAINTS;

DESC  USER_TAB_COLUMNS;

DESC USER_CONSTRAINTS;

--답
SELECT TABLE_NAME,COLUMN_NAME, DATA_TYPE, NULLABLE, DATA_DEFAULT,
    CONSTRAINT_NAME, CONSTRAINT_TYPE, R_CONSTRAINT_NAME
FROM USER_TAB_COLUMNS
--JOIN USER_CONSTRAINTS USING(TABLE_NAME);
NATURAL JOIN USER_CONSTRAINTS;

--3
SELECT BOOK_NO, BOOK_NM
FROM TB_BOOK
WHERE LENGTH(BOOK_NM) >= 25;

--4
SELECT WRITER_NM, OFFICE_TELNO, HOME_TELNO, MOBILE_NO
FROM(
SELECT WRITER_NM, OFFICE_TELNO, HOME_TELNO, MOBILE_NO
FROM TB_WRITER
WHERE MOBILE_NO LIKE '019%' AND WRITER_NM LIKE '김%'
ORDER BY 1
)
WHERE ROWNUM=1;

--5
SELECT COUNT(*) "작가(명)"
FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE = '옮김'
GROUP BY WRITER_NO;

--중복 제거한 답
SELECT SUM(
CASE 
WHEN COUNT(*)>=2 THEN 1
ELSE 1
END
) "작가(명)"
FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE = '옮김'
GROUP BY WRITER_NO;

--정은이 답
SELECT COUNT(*)
FROM (SELECT DISTINCT WRITER_NO
      FROM TB_BOOK_AUTHOR
      WHERE COMPOSE_TYPE = '옮김') F,
      TB_WRITER W
WHERE F.WRITER_NO = W.WRITER_NO;

--6
SELECT COMPOSE_TYPE, COUNT(*)
FROM TB_BOOK_AUTHOR
JOIN TB_BOOK USING (BOOK_NO)
WHERE COMPOSE_TYPE IN (
SELECT COMPOSE_TYPE, COUNT(*)
FROM TB_BOOK_AUTHOR
JOIN TB_BOOK USING (BOOK_NO)
WHERE COMPOSE_TYPE IS NOT NULL
GROUP BY COMPOSE_TYPE
HAVING COUNT(*)>=300
)
GROUP BY COMPOSE_TYPE;

SELECT COMPOSE_TYPE, COUNT(*)
FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE IS NOT NULL
GROUP BY COMPOSE_TYPE
HAVING COUNT(*)>=300;

--7
SELECT BOOK_NM, ISSUE_DATE, PUBLISHER_NM
FROM(
SELECT BOOK_NM, ISSUE_DATE, PUBLISHER_NM
FROM TB_BOOK
ORDER BY 2 DESC
)
WHERE ROWNUM = 1;

--8
SELECT WRITER_NM "작가 이름", 권수 "권 수"
FROM(
SELECT WRITER_NM, COUNT(*) 권수
FROM TB_BOOK_AUTHOR
JOIN TB_WRITER USING (WRITER_NO)
GROUP BY WRITER_NM
ORDER BY 2 DESC
)
WHERE ROWNUM  <= 3;

--9
SELECT * FROM TB_WRITER;-- WHERE REGIST_DATE IS NOT NULL;

UPDATE TB_WRITER
SET REGIST_DATE = (SELECT ISSUE_DATE
                    FROM ()
                    WHERE ROWNUM=1);
ROLLBACK;

SELECT WRITER_NM
FROM TB_BOOK_AUTHOR
JOIN TB_WRITER USING(WRITER_NO)
JOIN TB_BOOK USING (BOOK_NO)
GROUP BY WRITER_NM;

SELECT WRITER_NM--,ISSUE_DATE
FROM (
SELECT WRITER_NM
FROM TB_BOOK_AUTHOR
JOIN TB_BOOK USING(BOOK_NO)
JOIN TB_WRITER USING(WRITER_NO)
GROUP BY WRITER_NM
);
SELECT WRITER_

SELECT WRITER_NM FROM TB_WRITER
MINUS
SELECT WRITER_NM
FROM TB_BOOK_AUTHOR
JOIN TB_WRITER USING(WRITER_NO)
JOIN TB_BOOK USING (BOOK_NO)
GROUP BY WRITER_NM;

SELECT WRITER_NM, ISSUE_DATE
FROM TB_WRITER
WHERE ISSUE_DATE IN 
(
SELECT ISSUE_DATE
FROM TB_BOOK
                    )
GROUP BY WRITER_NM, ISSUE_DATE;

SELECT B.WRITER_NM
FROM(
SELECT WRITER_NM, ISSUE_DATE
FROM TB_BOOK_AUTHOR
JOIN TB_WRITER USING(WRITER_NO)
JOIN TB_BOOK USING (BOOK_NO)
GROUP BY WRITER_NM, ISSUE_DATE
ORDER BY 1)A , TB_WRITER B
WHERE A.WRITER_NM = B.WRITER_NM;



SELECT 

