--DAY9_2

--DDL (Data Definition Language) : 데이터 정의어
--CREATE, ALTER, DROP 
--데이터베이스 객체 만들고 수정하고 삭제하는 구문
--테이블(TABLE), 뷰(VIEW), 인덱스(INDEX), 시퀀스(SEQUENCE)
--사용자(USER), 롤(ROLE), 프로시저(PROCEDURE), 함수(FUNCTION)
--트리거(TRIGGER), 동의어(SYNONYM) 

--테이블 만들기
/*
CREATE TABLE 테이블명 (
    컬럼명  자료형(사이즈)  DEFAULT 기본값  제약조건,
    컬럼명  자료형(사이즈),
    .....,
    컬럼에 지정할 제약조건 
);
*/

DROP TABLE TEST;

CREATE TABLE TEST2 (
    ID  NUMBER(5),
    NAME CHAR(10 CHAR),
    ADDRESS VARCHAR2(50)
);

CREATE TABLE ORDERS(
    ORDERNO CHAR(4),
    CUSTNO CHAR(4),
    ORDERDATE DATE DEFAULT SYSDATE,
    SHIPDATE DATE,
    SHIPADDRESS VARCHAR2(40),
    QUANTITY NUMBER
);

COMMENT ON COLUMN ORDERS.ORDERNO IS '주문번호';
COMMENT ON COLUMN ORDERS.CUSTNO IS '고객번호';
COMMENT ON COLUMN ORDERS.ORDERDATE IS '주문일자';
COMMENT ON COLUMN ORDERS.SHIPDATE IS '배송일자';
COMMENT ON COLUMN ORDERS.SHIPADDRESS IS '배송주소';
COMMENT ON COLUMN ORDERS.QUANTITY IS '주문수량';

CREATE TABLE NOTICE(
    NOTICE_NO NUMBER,
    NOTICE_TITLE VARCHAR2(30),
    NOTICE_WRITER VARCHAR2(15),
    NOTICE_DATE  DATE DEFAULT SYSDATE,
    NOTICE_CONTENT VARCHAR2(2000),
    FILE_PATH VARCHAR2(50)
);

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '글번호';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '글제목';
COMMENT ON COLUMN NOTICE.NOTICE_WRITER IS '작성자아이디';
COMMENT ON COLUMN NOTICE.NOTICE_DATE IS '작성날짜';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '작성내용';
COMMENT ON COLUMN NOTICE.FILE_PATH IS '첨부파일경로명';

-- DML (Data Manupulation Language) : 데이터 조작어
-- INSERT, UPDATE, DELETE, TRUNCATE
-- 테이블에 데이터를 추가 기록하거나, 기록된 값을 수정하거나 행을 삭제하는 구문


CREATE TABLE DEPT(
    DEPT_ID CHAR(2),
    DEPT_NAME VARCHAR2(30) );
SELECT COUNT(*) FROM DEPT;
INSERT INTO DEPT VALUES ('20', '회계팀');
SELECT COUNT(*) FROM DEPT;
INSERT INTO DEPT VALUES ('10', '인사팀');
SELECT COUNT(*) FROM DEPT; --2
SELECT * FROM DEPT;