/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2019-03-12 09:40:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class memberDetailView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/member/../common/header.jsp", Long.valueOf(1552035300000L));
    _jspx_dependants.put("/views/member/../common/adminHeader.jsp", Long.valueOf(1551700616000L));
    _jspx_dependants.put("/views/member/../common/footer.jsp", Long.valueOf(1551698658000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"memberError.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	Member loginUser = (Member)session.getAttribute("loginUser");
	Member member = (Member)request.getAttribute("member");
	
	//취미 checked 처리
	String[] hobbies = member.getHobby().split(",");
	String[] checked = new String[9];
	for(String s : hobbies){
		switch(s){
		case "game":	checked[0] = "checked";  break;
		case "reading": checked[1] = "checked";  break;
		case "music":	checked[2] = "checked";  break;
		case "climb":	checked[3] = "checked";  break;
		case "sport":	checked[4] = "checked";  break;
		case "movie":	checked[5] = "checked";  break;
		case "travel":	checked[6] = "checked";  break;
		case "cook":	checked[7] = "checked";  break;
		case "etc":	checked[8] = "checked";  break;
		}
	}

      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>first</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/first/resources/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function(){\r\n");
      out.write("\t//암호확인 입력상자가 focus가 사라졌을 때\r\n");
      out.write("\t$(\"#userpwd2\").blur(function(){\r\n");
      out.write("\t\tconsole.log(\"포커스 사라짐.\");\r\n");
      out.write("\t\tvar pwd1 = $(\"#userpwd1\").val();\r\n");
      out.write("\t\tvar pwd2 = $(\"#userpwd2\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(pwd1 != pwd2){\r\n");
      out.write("\t\t\talert(\"암호와 암호확인이 일치하지 않습니다.\\n\"\r\n");
      out.write("\t\t\t\t+ \"다시 입력하십시요.\");\r\n");
      out.write("\t\t\t$(\"#userpwd1\").select();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
 if(loginUser != null && loginUser.getUserId().equals("admin")){ 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("header nav ul { list-style: none; } \r\n");
      out.write("header nav ul li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-right: 5px;\r\n");
      out.write("\tbackground: black;\r\n");
      out.write("}\r\n");
      out.write("header nav ul li a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding-top: 5px;\r\n");
      out.write("\tpadding-bottom: 0;\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("header nav ul li a:hover {\r\n");
      out.write("\tbackground: red;\r\n");
      out.write("\ttext-shadow: 1px 1px 2px white;\r\n");
      out.write("\tbox-shadow: 2px 2px 4px gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("<nav>\r\n");
      out.write("<ul>\r\n");
      out.write("\t<li><a href=\"/first/index.jsp\">home</a></li>\r\n");
      out.write("\t<li><a href=\"/first/mall\">회원관리</a></li>\r\n");
      out.write("\t<li><a href=\"\">공지사항관리</a></li>\r\n");
      out.write("\t<li><a href=\"\">게시글관리</a></li>\r\n");
      out.write("\t<li><a href=\"\">메뉴</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("</header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
 }else{ 
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>first</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("header nav ul { list-style: none; } \r\n");
      out.write("header nav ul li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-right: 5px;\r\n");
      out.write("\tbackground: orange;\r\n");
      out.write("}\r\n");
      out.write("header nav ul li a {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding-top: 5px;\r\n");
      out.write("\tpadding-bottom: 0;\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("\theight: 35px;\r\n");
      out.write("\tcolor: navy;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("header nav ul li a:hover {\r\n");
      out.write("\tbackground: olive;\r\n");
      out.write("\ttext-shadow: 1px 1px 2px white;\r\n");
      out.write("\tbox-shadow: 2px 2px 4px gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("<nav>\r\n");
      out.write("<ul>\r\n");
      out.write("\t<li><a href=\"/first/index.jsp\">home</a></li>\r\n");
      out.write("\t<li><a href=\"/first/nlist\">공지사항</a></li>\r\n");
      out.write("\t<li><a href=\"/first/blist?page=1\">게시글</a></li>\r\n");
      out.write("\t<li><a href=\"\">메뉴</a></li>\r\n");
      out.write("\t<li><a href=\"\">메뉴</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</nav>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
 } 
      out.write("\r\n");
      out.write("<hr style=\"clear:left;\">\r\n");
      out.write("<h1 align=\"center\">");
      out.print( member.getUserId() );
      out.write(" 님, 회원 정보 상세보기</h1>\r\n");
      out.write("<br>\r\n");
      out.write("<form action=\"/first/mupdate\" method=\"post\">\r\n");
      out.write("<table width=\"650\" align=\"center\">\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">아이디</th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"userid\" readonly \r\n");
      out.write("\t\tvalue=\"");
      out.print( member.getUserId() );
      out.write("\"> \r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">이 름</th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"username\" readonly \r\n");
      out.write("\t\tvalue=\"");
      out.print( member.getUserName() );
      out.write("\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">암 호</th>\r\n");
      out.write("\t\t<td><input type=\"password\" id=\"userpwd1\" \r\n");
      out.write("\t\tname=\"userpwd\" value=\"");
      out.print( member.getUserPwd() );
      out.write("\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">암호확인</th>\r\n");
      out.write("\t\t<td><input type=\"password\" id=\"userpwd2\" \r\n");
      out.write("\t\tvalue=\"");
      out.print( member.getUserPwd() );
      out.write("\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">성 별</th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t");
 if(member.getGender().equals("M")){ 
      out.write("\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"gender\" value=\"M\" checked> 남자 &nbsp; \r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"gender\" value=\"F\"> 여자\r\n");
      out.write("\t\t");
 }else{ 
      out.write("\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"gender\" value=\"M\"> 남자 &nbsp; \r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"gender\" value=\"F\" checked> 여자\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">나 이</th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<input type=\"number\" name=\"age\" min=\"20\" \r\n");
      out.write("\t\t\tmax=\"100\" value=\"");
      out.print( member.getAge() );
      out.write("\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">전화번호</th>\r\n");
      out.write("\t\t<td><input type=\"tel\" name=\"phone\" \r\n");
      out.write("\t\tvalue=\"");
      out.print( member.getPhone() );
      out.write("\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">이메일</th>\r\n");
      out.write("\t\t<td><input type=\"email\" name=\"email\" \r\n");
      out.write("\t\tvalue=\"");
      out.print( member.getEmail() );
      out.write("\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">취 미</th>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\" value=\"game\" ");
      out.print( checked[0] );
      out.write("> 게임</td>\r\n");
      out.write("\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\" value=\"reading\" ");
      out.print( checked[1] );
      out.write("> 독서</td>\r\n");
      out.write("\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\" value=\"music\" ");
      out.print( checked[2] );
      out.write("> 음악감상</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\" value=\"climb\" ");
      out.print( checked[3] );
      out.write("> 등산</td>\r\n");
      out.write("\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\" value=\"sport\" ");
      out.print( checked[4] );
      out.write("> 운동</td>\r\n");
      out.write("\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\" value=\"movie\" ");
      out.print( checked[5] );
      out.write("> 영화</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\" value=\"travel\" ");
      out.print( checked[6] );
      out.write("> 여행</td>\r\n");
      out.write("\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\" value=\"cook\" ");
      out.print( checked[7] );
      out.write("> 요리</td>\r\n");
      out.write("\t\t\t<td width=\"150\"><input type=\"checkbox\" name=\"hobby\" value=\"etc\" ");
      out.print( checked[8] );
      out.write("> 기타</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th width=\"150\">하고싶은말</th>\r\n");
      out.write("\t\t<td><textarea name=\"etc\" rows=\"3\" cols=\"30\" align=\"left\">");
      out.print( member.getEtc() );
      out.write("</textarea></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr height=\"40\">\r\n");
      out.write("\t\t<th colspan=\"2\">\r\n");
      out.write("\t\t<input type=\"submit\" value=\"수정하기\"> &nbsp; \r\n");
      out.write("\t\t<input type=\"reset\" value=\"작성취소\"> &nbsp; \r\n");
      out.write("\t\t<a href=\"/first/mdel?userid=");
      out.print( member.getUserId() );
      out.write("\">탈퇴하기</a>\r\n");
      out.write("\t\t&nbsp; &nbsp;\r\n");
      out.write("\t\t<a href=\"/first/index.jsp\">시작페이지로 이동</a>\r\n");
      out.write("\t\t</th>\t\t\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title></title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer align=\"center\">\r\n");
      out.write("copyright@kh.org 2019-03-04 master : 홍길동 <br>\r\n");
      out.write("tel : 02-1234-5678, 서울시 강남구 역삼동 777, fax : 02-1111-2356\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
