DROP TABLE USERS;
DROP TABLE BOARD;

CREATE TABLE USERS(
  USERID VARCHAR2(15),
  USERPWD VARCHAR2(15) NOT NULL,
  USERNAME VARCHAR2(25) NOT NULL,
  CONSTRAINT PK_USERS PRIMARY KEY (USERID)
);

COMMENT ON COLUMN USERS.USERID IS '사용자아이디';
COMMENT ON COLUMN USERS.USERPWD IS '사용자암호';
COMMENT ON COLUMN USERS.USERNAME IS '사용자이름';

INSERT INTO USERS VALUES ('user01', 'pass01', '홍길동');
INSERT INTO USERS VALUES ('user02', 'pass02', '유관순');
INSERT INTO USERS VALUES ('admin', 'admin', '관리자');

SELECT * FROM USERS;

CREATE TABLE BOARD(
	BOARD_NUM	NUMBER,	
	BOARD_WRITER	 VARCHAR2(20) NOT NULL,
	BOARD_TITLE	VARCHAR2(50) NOT NULL,
	BOARD_CONTENT	VARCHAR2(2000) NOT NULL,
	BOARD_FILE	VARCHAR2(100),
	BOARD_RE_REF	NUMBER DEFAULT 0,
	BOARD_RE_LEV	NUMBER DEFAULT 0,
	BOARD_RE_SEQ NUMBER DEFAULT 0,
	BOARD_READCOUNT	NUMBER DEFAULT 0,
	BOARD_DATE	DATE DEFAULT SYSDATE,
  CONSTRAINT PK_BOARD PRIMARY KEY (BOARD_NUM),
  CONSTRAINT FK_BOARD_WRITER FOREIGN KEY (BOARD_WRITER) REFERENCES USERS (USERID) ON DELETE SET NULL
);

COMMENT ON COLUMN BOARD.BOARD_NUM IS '게시글번호';
COMMENT ON COLUMN BOARD.BOARD_WRITER IS '작성자아이디';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD.BOARD_DATE IS '작성날짜';
COMMENT ON COLUMN BOARD.BOARD_FILE IS '첨부파일명';
COMMENT ON COLUMN BOARD.BOARD_RE_REF IS '원글번호';  -- 원글 : 0, 답글 : 원글번호
COMMENT ON COLUMN BOARD.BOARD_RE_LEV IS '답글단계'; -- 원글 : 0, 원글의 답글 : 1, 답글의 답글 : 2
COMMENT ON COLUMN BOARD.BOARD_RE_SEQ IS '답글순번'; -- 원글 : 0, 같은 원글의 답글일 때 : 1 ....... 순차처리

INSERT INTO BOARD 
VALUES (1, 'admin', '관리자 게시글', '저희 사이트를 이용해 주셔서 감사합니다.', NULL, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

SELECT * FROM BOARD;

COMMIT;
